### ISSUE TITLE
Save to image not working

### ISSUE THREAD

**Issue by nema69** [Archie-Adams/keyboard-shortcut-map-maker#4]
Hey, first of all: I really like your project and have used it quite a few times :)
Today i notice that I can't save to image, it seems because the relevant javascript libraries aren't hosted where they used to be.
![image](https://github.com/Archie-Adams/keyboard-shortcut-map-maker/assets/61890712/0ac2c29b-ca69-4bbc-b5c4-27f504b75e45)
Should be an easy fix :)

**Comment by Archie-Adams** [comment]
That's great to hear thank you, I'm currently working on a v2 which should make things easier to use! 

Seems like the default build process changed at some point to exclude the node_modules, I think this should be fixed with 654d3d9 now.
